// auto-generated by scripts/build.ts
export const VERSION = "1.0.0";
export const VERSION_TAG = "v1.0.0";
export const COMMIT = "unknown";
export const PUBLISHER_NAME = "rkriad585";
export const PUBLISHER_EMAIL = "rkriad585@gmail.com";
