#!/usr/bin/env bun
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, "..");

const versionTag = readFileSync(join(root, ".version"), "utf-8").trim();
const version = versionTag.replace(/^v/, "");

const commit = process.env.COMMIT_SHA
  ?? (() => { try { return execSync("git rev-parse --short=8 HEAD", { encoding: "utf-8" }).trim(); } catch { return "unknown"; } })();

const publisherName = process.env.PUBLISHER_NAME ?? "rkriad585";
const publisherEmail = process.env.PUBLISHER_EMAIL ?? "rkriad585@gmail.com";

const versionModule = `// auto-generated by scripts/build.ts
export const VERSION = ${JSON.stringify(version)};
export const VERSION_TAG = ${JSON.stringify(versionTag)};
export const COMMIT = ${JSON.stringify(commit)};
export const PUBLISHER_NAME = ${JSON.stringify(publisherName)};
export const PUBLISHER_EMAIL = ${JSON.stringify(publisherEmail)};
`;

const versionPath = join(root, "src", "core", "__version.ts");

const originalContent = existsSync(versionPath)
  ? readFileSync(versionPath, "utf-8")
  : null;

writeFileSync(versionPath, versionModule, "utf-8");

const targetArg = process.argv.find((a) => a.startsWith("--target="));
const target = targetArg ? targetArg.split("=")[1] : "bun-windows-x64";

const outfileArg = process.argv.find((a) => a.startsWith("--outfile="));
const defaultOutfile = join(root, "dist", "neorwc");
const outfile = outfileArg ? outfileArg.split("=")[1] : defaultOutfile;

console.log(`Building neorwc ${versionTag} (target: ${target}, commit: ${commit})...`);

await Bun.write(join(root, "dist", "build.env"), [
  `VERSION=${version}`,
  `COMMIT=${commit}`,
  `PUBLISHER_NAME=${publisherName}`,
  `PUBLISHER_EMAIL=${publisherEmail}`,
].join("\n"));

const proc = Bun.spawnSync([
  "bun",
  "build",
  "--compile",
  `--target=${target}`,
  join(root, "neorwc.ts"),
  "--outfile",
  outfile,
]);

if (proc.stdout.length) writeFileSync(join(root, "dist", "build.log"), proc.stdout.toString());
if (proc.stderr.length) console.error(proc.stderr.toString());

if (originalContent) {
  writeFileSync(versionPath, originalContent, "utf-8");
} else {
  writeFileSync(
    versionPath,
    `// placeholder — regenerated by scripts/build.ts at build time
export const VERSION = "0.0.0";
export const VERSION_TAG = "v0.0.0";
export const COMMIT = "unknown";
export const PUBLISHER_NAME = "rkriad585";
export const PUBLISHER_EMAIL = "rkriad585@gmail.com";
`,
    "utf-8",
  );
}

process.exit(proc.exitCode);
