#!/usr/bin/env bun
// Read .version and inject it into the compiled binary
// by generating src/core/__version.ts at build time
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, "..");

// read the version from .version file
const versionTag = readFileSync(join(root, ".version"), "utf-8").trim();
const version = versionTag.replace(/^v/, "");

// generate the version module with injected values
const versionModule = `// auto-generated by scripts/build.ts
export const VERSION = ${JSON.stringify(version)};
export const VERSION_TAG = ${JSON.stringify(versionTag)};
`;

const versionPath = join(root, "src", "core", "__version.ts");

// save original content if it exists (to restore later)
const originalContent = existsSync(versionPath)
  ? readFileSync(versionPath, "utf-8")
  : null;

// write the injected version module
writeFileSync(versionPath, versionModule, "utf-8");

// determine target from args, default to current platform
const targetArg = process.argv.find((a) => a.startsWith("--target="));
const target = targetArg ? targetArg.split("=")[1] : "bun-windows-x64";

console.log(`Building neorwc ${versionTag} (target: ${target})...`);

const proc = Bun.spawnSync([
  "bun",
  "build",
  "--compile",
  `--target=${target}`,
  join(root, "neorwc.ts"),
  "--outfile",
  join(root, "dist", "neorwc"),
]);

if (proc.stdout.length) writeFileSync(join(root, "dist", "build.log"), proc.stdout.toString());
if (proc.stderr.length) console.error(proc.stderr.toString());

// restore original content or remove generated file
if (originalContent) {
  writeFileSync(versionPath, originalContent, "utf-8");
} else {
  // write a placeholder so imports won't break in source mode
  writeFileSync(
    versionPath,
    `// placeholder — regenerated by scripts/build.ts at build time
export const VERSION = "0.0.0";
export const VERSION_TAG = "v0.0.0";
`,
    "utf-8",
  );
}

process.exit(proc.exitCode);
